package com.geektechkb.feature_auth.utils

import androidx.appcompat.app.AppCompatActivity
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.PhoneAuthProvider

typealias NotAnActualActivity = AppCompatActivity
typealias NotAnActualFirebaseAuth = FirebaseAuth
typealias NotAnActualPhoneAuthProviderCallbacks = PhoneAuthProvider.OnVerificationStateChangedCallbacks